# AI每日简报 - Hugo 站点配置
baseURL = "https://aiheadline.news/"
title = "AI每日简报 - 您的人工智能情报站"
languageCode = "zh-cn"
enableRobotsTXT = true
enableGitInfo = false
enableEmoji = true
hasCJKLanguage = true

# 构建配置
[build]
writeStats = true

# Markdown 配置
[markup]
[markup.goldmark]
[markup.goldmark.renderer]
unsafe = true

[markup.highlight]
style = "github"
lineNos = true

# Hugo 模块配置
[module]
[[module.imports]]
path = "github.com/imfing/hextra"

# 站点参数
[params]
description = "精选全球AI突破性进展：大模型发布、技术突破、产业应用、投融资事件、学术前沿。每日定时更新，3分钟速览AI界大事。"
rssFullContent = true

# 主题外观配置
[params.theme]
appearance = "auto"
displayToggle = true

# 导航栏配置
[params.navbar]
displayTitle = false
displayLogo = true

[params.navbar.logo]
path = "images/logo.png"
dark = "images/logo-dark.png"
width = 175
height = 50

# 页脚配置
[params.footer]
enable = true
displayCopyright = false
displayPoweredBy = false

# 页面配置
[params.page]
width = "normal"

# 搜索配置
[params.search]
enable = true
type = "flexsearch"

[params.search.flexsearch]
index = "content"
tokenize = "forward"
threshold = 0.2

# 侧边栏配置
[params.sidebar]
enable = true

# 编辑链接配置
[params.editURL]
enable = false

# 主菜单配置
[[menu.main]]
identifier = "documentation"
name = "首页"
pageRef = "/"
weight = 1

[[menu.main]]
identifier = "search"
name = "搜索"
weight = 5
[menu.main.params]
type = "search"

[[menu.main]]
name = "GitHub"
weight = 10
url = "https://github.com/YYvanYang/AIHeadline.news"
[menu.main.params]
icon = "github"

[[menu.main]]
name = "Telegram"
weight = 11
url = "https://t.me/ai_daily_briefing"
[menu.main.params]
icon = "telegram"

[[menu.main]]
name = "RSS"
weight = 12
url = "/index.xml"
[menu.main.params]
icon = "rss"

# 输出格式配置
[outputs]
home = ["HTML", "RSS"]
page = ["HTML"]
section = ["HTML", "RSS"]

# 服务配置
[services]
[services.rss]
limit = 20

[services.googleAnalytics]
ID = "G-0DRRQBXZWN"

# 缓存配置
[caches]
[caches.assets]
maxAge = "720h"

[caches.getcsv]
maxAge = "60s"

[caches.getjson]
maxAge = "60s"

[caches.getresource]
maxAge = "60s"

[caches.images]
maxAge = "720h"

[caches.modules]
maxAge = "720h"

# 安全配置
[security]
enableInlineShortcodes = false

[security.funcs]
getenv = ["^HUGO_", "^CI$"]

[security.http]
methods = ["(?i)GET|POST"]
urls = [".*"]
